### ISSUE TITLE
[FEAT] Compatibility with the MPMB Sheet

### ISSUE THREAD

**Issue by revilowaldow** [arcanistzed/pdf-sheet#1]
[See https://www.flapkan.com/](https://www.flapkan.com/)

**Comment by arcanistzed** [comment]
Unfortunately, these PDFs aren't supported by [pdfform.js](https://github.com/phihag/pdfform.js) which is the library the module uses because they have buttons and embedded JavaScript. You should submit a bug there instead, but it likely won't be fixed because the repo doesn't seem very active. Sorry :/

**Comment by revilowaldow** [comment]
That's fine, MPMB has its own import sources anyway. Cheers for looking at it.
