### ISSUE TITLE
  Compatibility for 3.5 SRD

### ISSUE THREAD

**Issue by valhallatoys** [arcanistzed/pdf-sheet#11]
PLease make compatibley for dnd 3.5 srd

**Comment by arcanistzed** [comment]
The module is system agnostic and works for all systems including D&D 3.5 although you'll need a mapping in order to have it fill in the fields automatically. See [the instructions for creating one here in the README](https://github.com/arcanistzed/pdf-sheet#mapping). Let me know if you have any questions or need help. I have helped community members create mappings on my Discord server for both systems which already have one.
