### ISSUE TITLE
Compact PDF sheet like on fastcharacter.com with mergeable areas

### ISSUE THREAD

**Issue by FreakyFerrox** [arcanistzed/pdf-sheet#35]
### Problem

The classic sheet for characters need 2 sides/pieces of paper and the text box grafics layout consume a lot of space.
So a nice sleak and minimalistic character sheet would be nice, like that from fastcharacter.com

### Solution

Create a Fillable Form PDF which can merge areas to the amaount of text-content and write the mapping code for it.

### Alternatives

Create a fillable form without mergeable areas.

### Context

Text Boxes need a lot of space and don't merge to text size.
[Modin the Chosen.pdf](https://github.com/arcanistzed/pdf-sheet/files/8277507/Modin.the.Chosen.pdf)
Lot of information and well organized and there is still space left. It's even in letter format and not A4.
[Fast Character _ D&D Character Maker _ Human Paladin 12 (Oath of Glory).pdf](https://github.com/arcanistzed/pdf-sheet/files/8277558/Fast.Character._.D.D.Character.Maker._.Human.Paladin.12.Oath.of.Glory.pdf)

**Comment by arcanistzed** [comment]
Mappings and the form-fillable PDFs are community contributed and not something that need to be created as part of the module itself. I deliberately made this very extensible to avoid working on this sort of thing, so, if you are interested in this, I suggest making it yourself :slightly_smiling_face:
I'll close the issue because it doesn't actually relate to the module code.
